update pre-commit to remove whitespace

diff --git a/src/texproject/templates/pre-commit b/src/texproject/templates/pre-commit
--- a/src/texproject/templates/pre-commit
+++ b/src/texproject/templates/pre-commit
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # hook is called before each commit to verify that there are no errors
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
@@ -21,5 +21,52 @@ EOF
     exit 1
 fi
 
-# If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
+# Fix whitespace errors
+# detect platform
+platform="win"
+uname_result=`uname`
+if [ "$uname_result" = "Linux" ]; then
+  platform="linux"
+elif [ "$uname_result" = "Darwin" ]; then
+  platform="mac"
+fi
+
+# change IFS to ignore filename's space in |for|
+IFS="
+"
+# autoremove trailing whitespace
+for line in `git diff --check --cached | sed '/^[+-]/d'` ; do
+  # get file name
+  if [ "$platform" = "mac" ]; then
+    file="`echo $line | sed -E 's/:[0-9]+: .*//'`"
+  else
+    file="`echo $line | sed -r 's/:[0-9]+: .*//'`"
+  fi
+  # display tips
+  echo -e "auto remove trailing whitespace in \033[31m$file\033[0m!"
+  # since $file in working directory isn't always equal to $file in index, so we backup it
+  mv -f "$file" "${file}.save"
+  # discard changes in working directory
+  git checkout -- "$file"
+  # remove trailing whitespace
+  if [ "$platform" = "win" ]; then
+    # in windows, `sed -i` adds ready-only attribute to $file(I don't kown why), so we use temp file instead
+    sed 's/[[:space:]]*$//' "$file" > "${file}.bak"
+    mv -f "${file}.bak" "$file"
+  elif [ "$platform" == "mac" ]; then
+    sed -i "" 's/[[:space:]]*$//' "$file"
+  else
+    sed -i 's/[[:space:]]*$//' "$file"
+  fi
+  git add "$file"
+  # restore the $file
+  sed 's/[[:space:]]*$//' "${file}.save" > "$file"
+  rm "${file}.save"
+done
+
+if [ "x`git status -s | grep '^[A|D|M]'`" = "x" ]; then
+  # empty commit
+  echo
+  echo -e "\033[31mNO CHANGES ADDED, ABORT COMMIT!\033[0m"
+  exit 1
+fi
